FROM python:3.13.3-alpine3.21

WORKDIR /usr/src/app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN apk add --no-cache tcpdump iptables

CMD ["python", "./test/test.py"]